[project]
name = "deltaGen"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "PyQt6>=6.6.0",
]

[project.scripts]
deltagen-gui = "src.main:main"

[build-system]
requires = ["setuptools>=75.0"]
build-backend = "setuptools.backends._legacy:_Backend"
